import olympiad;
import cse5;
size(6cm);
defaultpen(fontsize(9pt));

pair A = (-1,1);
pair B = (-1,-1);
pair C = (1,-1);
pair D = (1,1);
pair E = (0, 0.5);
draw(A -- B -- C -- D -- cycle);
filldraw(A -- (0,0) -- B -- cycle, red + opacity(0.1));
filldraw(B -- (0,0) -- C -- cycle, green + opacity(0.1));
filldraw(C -- (0,0) -- D -- cycle, blue + opacity(0.1));
filldraw(D -- (0,0) -- A -- cycle, grey + opacity(0.1));
draw(A -- E -- D);
draw(B -- E -- C);
label("$A$", A, NW);
label("$B$", B, SW);
label("$C$", C, SE);
label("$D$", D, NE);
label("$E$", E, dir(90));
dot(A);
dot(B);
dot(C);
dot(D);
dot(E);
dot((0,0), purple);
dot(IP(E -- B, A -- C), purple);
dot(IP(E -- C, B -- D), purple);
